# app
app:
  name: diky2020-backend
  env: production

# net
net:
  port: 9000

# security data
security:
  donioValidationToken: donio-token
  recaptcha:
    siteKey: recaptcha-site-key
    secretKey: recaptcha-secret-key

# database configuration
database:
  host: database.host.url
  port: 27017
  name: database_name
  user: username
  password: password

# rabbitmq configuration
queue:
